### ISSUE TITLE
Broken Autorefresh on add/rename/move/delete notes on Windows

### ISSUE THREAD

**Issue by graphixillusion** [Linus-Mussmaecher/rucola#4]
Actually when you add/rename/move/delete a note, the list is not automatically refreshed and rucola must be restarted to see the changes.

**Comment by Linus-Mussmaecher** [comment]
Judging by your other question, you are using windows.
As this problem does not happen on my Linux machine, I have tagged the issue as windows.

Can you maybe give more specific information about your operating system, and what method your are using to add/rename/move/delete a note? Are you using rucola's internal features, or are you doing the modifications from an external source (like the Windows Explorer)?

I did most of the development on Linux and tried to only use cross-plattform libraries, but I have not done extensive testing beyond a simple compilation + install on Windows or Mac.
Specifically, the library used for tracking file changes is [notify](https://github.com/notify-rs/notify) which explicitly specifies windows support.

I will try to look into this more in the coming week(end).
If issues like this keep piling up, I might simply have to remove support for Windows, as my focus is on the unix version.

**Comment by graphixillusion** [comment]
Yes correct i'm using Windows. Actually it doesn't work in both ways: using windows explorer and using rucola's internal features. It never refreshes on any changes.

**Comment by Linus-Mussmaecher** [comment]
Then I suppose that this is in fact a problem with `notify`.
I will investigate it and inform you of anything I can find/fix.

**Comment by Linus-Mussmaecher** [comment]
I tracked the issue down - Unix sends three events on a file rename: One containing the source, one containing the target and one containing both. Windows only sends the first two.
I was only relying on the third one, so renames and modifies were ignored.

The problems with creation and deletion were related to mixing `/` and `\` in file paths, as the `ignore` create seems to create paths with `/` while the `notify` crate uses paths with `\`.

All of this should be fixed in the next release `0.3.4` coming (probably) tomorrow.
Thank you for your patience!
