### ISSUE TITLE
Add warning when launching rucola in home directory

### ISSUE THREAD

**Issue by StevenBlack** [Linus-Mussmaecher/rucola#7]
**This is an anecdotal problem, but it may be helpful to know...**

I installed rucola according to docs.  All-good!

**EXCEPT...**

My terminal app defaults to my home `~/` folder.  So when I...

```
$ rucola
```

... I get a message that says `...indexing` and this continued for about a minute before I `ctrl+c` knowing what is happening because, I'm old.

**SUGGESTIONS**

1. The rucola docs should state, "*Start Rucola in your notes folder*" or words to that effect.
2. Rucola should probably exit with a message, or ask for a Yes "Y" confirmation, if the user invokes rucola from `$HOME`.  Because this is typically never what the user should do.

**Comment by Linus-Mussmaecher** [comment]
The actual folder traversal in rucola is based on `ripgrep`, so it should be rather fast.
Of course, if your home folder contains a lot of markdown files deep down, all of those have to actually be read (unlike other file types, which are just discarded immediately) in order to check for links to other notes.
I guess if you have a large file system (with lots of irrelevant markdown files) or very slow hardware, this might take a while.

Just as a fail safe, does your config file still have `file_types = ["markdown"]`?
Because if you put the wrong file filter there, rucola attempts to read the contents of every single file it encounters, which obviously takes a very long time.
However, nothing bad will happen if the entry is simply missing - except that rucola won't track files of any file type.

That being said, a warning in the docs is certainly a good idea, and a warning when launching in `$HOME` probably won't hurt either. I'll update the docs now and see that the next version will contain such a warning.

**Comment by Linus-Mussmaecher** [comment]
Such a warning has been added and will be contained in the next release.
I chose to simply put it in the same screen as the `Indexing...` message, because either you are stuck there for long enough to read it or there is not problem.

**Comment by Linus-Mussmaecher** [comment]
Such a warning has been added and will be contained in the next release.
I chose to simply put it in the same screen as the `Indexing...` message, because either you are stuck there for long enough to read it or there is not problem.

**Comment by alperyilmaz** [comment]
sorry for replying to closed issue but I didnt think my question reserves a new issue. 
I accidentally ran rucola at home directory and indexing took long time. 
My question is, is there any index file generated and kept somewhere? I'm guessing it would be large, I wanted to delete it but couldn't find any index file.

thanks.

**Comment by Linus-Mussmaecher** [comment]
Hi,

currently, no index file is being generated.
If you have HTML conversion activated (as it is by default), the folder `.html` will be created in the respective directory and can be deleted safely.
